[build]
  publish = "public"
  command = "npm run build"

[dev]
  autoLaunch = false
  framework = "#custom"
  targetPort = 8080
  command = "npm run dev"

[[redirects]]
  from = "/monologue"
  to = "/"
  status = 200
  force = true

[[redirects]]
  from = "/interview"
  to = "/"
  status = 200
  force = true

[[redirects]]
  from = "/pair-programming"
  to = "/"
  status = 200
  force = true

[[redirects]]
  from = "/solo"
  to = "/"
  status = 200
  force = true

[[plugins]]
  package = "netlify-plugin-toast-cache"
